travis:
  secure:
    BINSTAR_TOKEN: TTyRdOn3ly4A6+ym0C6YGrG5dy6MEc1MvG5KkAwJ9cln88JPKikZK2mVDCH2Cr6nTSx9Jx8lZFVL5D2Q2w53mzvHOie8RnOxFAVCwPOFCwk+kq/ScBgIulbHMgcI/v7SbBUyjY7MF3+NK5LpVrcAe9adaAjxGtKFRYQpmJv3OiDkP+hkg4+Hs2DYCsaPTDkuaPMGmvTXWUaOwhVoOrUBJEVs1nJBCwaL58qNZzJ6Lpt9W7zAoaC+3KQx0p57WxhAt/qd2jsS9AHBKQ/48WeIcoKPOBYdWWZ4WK0hng55rZFthRxwX6rRq3yZvQ2TiGD1B+F7/2SuEG+NO8OIfWz28cDe7tanVzj5uzw96oTx5FCToEwB5pKgUgpW1SvL1qBqFK6LntR+O/nG6j9vUUXO5SQ5V75oUSLk6ATwPBuat14NEyIqe8uwfWz5Ne+u8i8mPgqLw0jpd2lpLKd4X5HmqWWprjO0lMBmlsF0vUzrSmjYvaZnINqtoCy6jXHu10T+RgnamzY5MptTX5jwqvu9WQb7oHjJLAbADnh6laD2adKl9TlI1pmsGi/xQ9WyDMQI795KqCp//M2xZzSJm9Ut+K94AHn597hXte6AyE0iN7reaHItboffdneqsYHuSfMyHQ0mdmQTCVWRtpgmwPCbikraPAjxKyfay0IxIfuTcTA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
